name:                flex-key
version:             0.1.0.0
github:              "rgreenblatt/flex-key"
license:             MIT
author:              "Ryan Greenblatt"
maintainer:          "ryan_greenblatt@brown.edu"
copyright:           "2020 Ryan Greenblatt"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/rgreenblatt/flex-key#readme>

dependencies:
- base >= 4.7 && < 5
- evdev >= 1.2

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  flex-key-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flex-key

tests:
  flex-key-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flex-key
